### ISSUE TITLE
数据库中保存观察目标的文章标题

### ISSUE THREAD

**Issue by MamaShip** [MamaShip/Observer#53]
为了用户端显示友好，期望用户查询 list 等命令时可以同时看到**标题**与**地址**。因此在第一次抓取网页进行备份时，把文章标题也存一下。

这个改动可能较大，还需要验证 MySQL 存储中文字符串时的兼容性问题。

优先级：低

**Comment by MamaShip** [comment]
我们可以把 alpha 测试结束的时间点提前一点，（例如6月25号），用来验证一下这个改动。

@ChenliangLi205 我之前的想法是，article checker 调 update_article_status 时，把文章标题填入optionals 这个 dict 里。observer 去更新数据库时就可以 try 获取这个 optionals["title"]，如果有就存入数据库，没有也不影响整个流程。（title 字段在数据库里也设定为可选项，允许为空）

目前代码里 update_article_status 就支持这样用：
```python
def update_article_status(article_id, valid, backup_path=None, optionals={}):
    """Do jobs when article status changed.

    Args:
        article_id : int
        valid : bool
        backup_path : str
        optionals : dict 
            maybe contains: "reason" shows why status changed
                            "title" shows article title detected
    Returns:
        success: bool
    """
```

**Comment by ChenliangLi205** [comment]
可以的
