### ISSUE TITLE
Article_Checker 记录的日志冲日志了

### ISSUE THREAD

**Issue by MamaShip** [MamaShip/Observer#71]
在 test_release 分支上进行了测试。

Article_Checker日志中持续大量记录：
`article_checker - ERROR - checker queue get error`

导致正常日志被冲掉

另外，app.log 里也记了一些类似日志。要研究下为什么记过去了

**Comment by ChenliangLi205** [comment]
已定位BUG原因：checker_queue空了之后checker还会不断去取，取了就会报错
我寻思得改成唤醒机制

**Comment by MamaShip** [comment]
closed by #73
